FROM dockerfile/java:oracle-java8

ENV DATOMIC_VERSION 0.9.5067

RUN curl -LOk https://my.datomic.com/downloads/free/$DATOMIC_VERSION.zip \
  && unzip datomic-pro-$DATOMIC_VERSION.zip \
  && mv datomic-pro-$DATOMIC_VERSION datomic \
  && cd datomic

ENV PATH $PATH:/data/datomic/bin

ADD free-transactor.properties /data/datomic/

EXPOSE 4334 4335

CMD ["transactor", "/data/datomic/free-transactor.properties"]